### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by keybounce** [penteract/5DPGNRecorderLinux#1]
Sadface, and I do not know how to proceed.

I have the windows client running under steam / proton on my linux machine.

```
user@NS70PU:/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux$ python3 recordgame.py 
found process with id 141275
Traceback (most recent call last):
  File "/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux/recordgame.py", line 146, in <module>
    gr = GameRecorder(*get_mem(pid))
  File "/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux/recordgame.py", line 19, in get_mem
    if m.group(5)==b"00:00" and m.group(7)==b"\n":
AttributeError: 'NoneType' object has no attribute 'group'
user@NS70PU:/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux$ python3 findboards.py 
Traceback (most recent call last):
  File "/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux/findboards.py", line 37, in <module>
    mem,nms = get_mem(s[0])
  File "/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux/findboards.py", line 20, in get_mem
    name = str(m.group(7),encoding="ascii")
AttributeError: 'NoneType' object has no attribute 'group'
user@NS70PU:/media/user/Transfer/New files/Downloads/5d/5DPGNRecorderLinux$ 
```

**Comment by penteract** [comment]
This PGN recorder is designed to work with the native linux version of the game, not the Windows one running through proton (the memory layout for the windows version is similar, so it might not be too hard to get this to work).
You might be able to run the Windows PGN recorder through proton as well, but that may not be straightforward.
(I said that on discord, but I'll put it here as well in case someone else looks here)
